### ISSUE TITLE
Field validation when adding Service Provider informaiton.

### ISSUE THREAD

**Issue by OmarAlmo** [SEG2105-Group/JobZi#107]
All fields are validated. This includes:
- [ ] date (should not be able to create availability of a past date)
- [ ] address

**Comment by RawadAboudlal** [comment]
Adding of user information for the service provider has been implemented in pull request #109 with validation. However, the validation may not hav been fully tested.

**Comment by RawadAboudlal** [comment]
Fixed an issue with password validation in pull request #137.

**Comment by RawadAboudlal** [comment]
This should be closed but it is not yet closed because I have not checked every single field to make sure it works correctly.

**Comment by RawadAboudlal** [comment]
Going to assume this is okay...
