### ISSUE TITLE
services

### ISSUE THREAD

**Issue by Mo-Shehri** [SEG2105-Group/JobZi#39]
Admin. Adding ,modifying ,removing  services

adding : Can add services. A service has a name and hourly rate.
Ex. Furniture assembly, 100$ hourly rate. 

removing: Can remove services no longer offered

Modify/Edit : Can edit services.
Ex. Furniture assemble, 120$ hourly rate. 

***All fields are validated. For instance, you should not be able to create a
service with no name. This should be implemented along with valid
error messages.
(-1 for each field in which the user input is not validated)***

**Comment by RawadAboudlal** [comment]
Poorly-phrased/little-effort issue. Has been replaced with much more appropriate issues.
