### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by Mo-Shehri** [SEG2105-Group/JobZi#40]
Integration with CircleCI to see the automated builds and automated testing. This will become mandatory for deliverable 4.

**Comment by RawadAboudlal** [comment]
Seems to be failing all tests for no apparent reason.

**Comment by RawadAboudlal** [comment]
Fixed in pull request #56.

**Comment by RawadAboudlal** [comment]
Issue fixed in latest version. Also added CircleCI banner.
