### ISSUE TITLE
build.gradle (Module: app)  | Dependecies

### ISSUE THREAD

**Issue by Mo-Shehri** [SEG2105-Group/JobZi#45]
Make sure the build.gradle file lists all the correct dependencies.

Android Studio is showing there are some errors with mismatching versions and obsolete versions. This should ideally be sorted out but is not of high priority.

**Comment by RawadAboudlal** [comment]
This issue appears to work fine on my version of the repository. This could be a per-person issue.

**Comment by RawadAboudlal** [comment]
Fixed in pull request #56.
